### PR TITLE
UI/ UX Improvements

### PR DESCRIPTION
**Pull request by frzkn**
Fix - Location suggestions didn't close on losing focus,
Fix - Data-grid cards didn't center on smaller screens,
Improve - UI of cards to better represent the data by using icon for location and source

### CODE REVIEW

**Comment by yogesh-hackx** [comment]
Appreciate your efforts man!,
Card styling improvements are good, Autocomplete patch has some issues, like, options hide when a suggestion is clicked without that suggestion being filled in the search box.

**Comment by tejasa97** [comment]
@yogesh-hackx can you look into this PR and merge if it all looks good?

**Comment by yogesh-hackx** [comment]
> @yogesh-hackx can you look into this PR and merge if it all looks good?

Yup was just looking into code, looks good

**Comment by yogesh-hackx** [comment]
Yupp, works now!!👍

**Pull request merged**
